# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import youtube_pb2 as proto_dot_youtube__pb2


class YoutubeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SearchYoutubeMusic = channel.unary_unary(
        '/youtube.YoutubeService/SearchYoutubeMusic',
        request_serializer=proto_dot_youtube__pb2.YtMusicRequest.SerializeToString,
        response_deserializer=proto_dot_youtube__pb2.YtMusicReply.FromString,
        )
    self.DownloadYoutubeMusic = channel.unary_unary(
        '/youtube.YoutubeService/DownloadYoutubeMusic',
        request_serializer=proto_dot_youtube__pb2.YtMusicRequest.SerializeToString,
        response_deserializer=proto_dot_youtube__pb2.YtMusicReply.FromString,
        )


class YoutubeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SearchYoutubeMusic(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadYoutubeMusic(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YoutubeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SearchYoutubeMusic': grpc.unary_unary_rpc_method_handler(
          servicer.SearchYoutubeMusic,
          request_deserializer=proto_dot_youtube__pb2.YtMusicRequest.FromString,
          response_serializer=proto_dot_youtube__pb2.YtMusicReply.SerializeToString,
      ),
      'DownloadYoutubeMusic': grpc.unary_unary_rpc_method_handler(
          servicer.DownloadYoutubeMusic,
          request_deserializer=proto_dot_youtube__pb2.YtMusicRequest.FromString,
          response_serializer=proto_dot_youtube__pb2.YtMusicReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'youtube.YoutubeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
